### ISSUE TITLE
Kong downtime during rolling updates

### ISSUE THREAD

**Issue by cadiegoc** [giantswarm/kong-app#73]
Hi, we've discussed this a bit in the last meetings, where we talked about readiness probes of Kong not working as expected.
The last theory (only a theory) it's that the readiness probe are okay, the Kong pods are okay and ready to work in a few seconds, but the problem might be in the AWS LoadBalancer not finding the new Kong pods. Hence the downtime.
PDF with all info from our ticket: [KONG-475.pdf](https://github.com/giantswarm/kong-app/files/5297324/KONG-475.pdf)

In our AWS Kong clusters we're using Kubernetes Services (LoadBalancer type, also "AWS NetworkLoadBalancer" type), with External Traffic Policy=Local.

Thank you for your time.

**Comment by cadiegoc** [comment]
As you'll see in the PDF attached in the previous comment, the minReadySeconds configuration looked promising, but doing performance tests with thousands requests per second, or just doing manual curls, I saw that some requests arrived to the new Kong pods, but some of them didn't arrive to the Kong pod at all. This behaviour of "some requests get to the new Kong pod, some requests don't" continues for 1-2 minutes, and after that, it works 100%:
![imagen](https://user-images.githubusercontent.com/38490820/94531360-c1f0a900-023c-11eb-8749-c0a563e50ca5.png)

**Comment by cadiegoc** [comment]
One more update:
I tested a rolling update using 50% of surge. These are the parameters:

    - 2 Kong pods
    - MinReadySeconds = 180 seconds
    - RollingUpdateStrategy: 0% max unavailable, 50% max surge
    - To trigger the rolling update, we just increase the RAM limit from 2400Mi to 2401Mi
    - Neoload test: 500 Users, 10 minutes (we expect thousands of requests per second, 3000-9000 depending on the number of Kong pods)

This is what happens during the rolling update:

    - 00:05-00:10 - A third pod gets created, Ready and Running (Containers 2/2), but not Available yet (MinReadySeconds = 180 seconds) in a new Kubernetes node, with the new configuration (RAM 2401Mi)
    - 02:00-02:10 - In the logs of the pod, we can see that it starts getting lots of traffic, hundreds or thousands of logs of traffic. But the pod is still not Available, the MinReadySeconds is 3 minutes but it has been only 2 minutes or so. The AWS LoadBalancer is ignoring Kubernetes.
    - 03:00-03:10 - A fourth pod, a new one, is trying to get created, but it's apie1 Kubernetes cluster, there are not enough Kubernetes nodes yet. So the fourth pod is not created yet, it's Pending.
    - 03:10-03:15 - One of the old pods gets a Terminated status, and finally gets completely deleted.
    - 03:16 - The fourth pod, which was in Pending state, starts to get created, in the same Kubernetes node as the old pod that just got deleted. It's now getting created, "Containers 0/2"
    - 03:18-03:20 - The fourth pod changes to "Containers 1/2"
    - 03:20-03:22 - The fourth pod changes to "Containers 2/2" and it's Ready and Running, but not Available yet (MinReadySeconds = 180 seconds).
    - 03:24 - It's only been 2 seconds since the fourth pod has been created, and in its logs we're already seeing hundreds or thousands of traffic logs per second. It's already accepting traffic, just 2 seconds after getting Ready. But it's not Available yet (MinReadySeconds = 180 seconds), so once again, AWS LoadBalancer is ignoring Kubernetes. I think it got traffic from AWS LoadBalancer that fast, after just 2 seconds, probably because the pod got created in the same Kubernetes node as one of the old pods that got deleted.
    - 06:00 - 06:10 - The last old pod gets deleted. We don't see downtime or error calls. Maybe expected them, since it's been reported in the previously mentioned Github bug issue (https://github.com/Kong/kubernetes-ingress-controller/issues/581 ), but we didn't experience them. Don't know if , since the fourth pod got created in the same Kubernetes node as an old Kong pod, it affected the outcome (having the IPs deleted in the Loadbalancer, hence having downtime) or not.

Neoload test link: http://neoloadweb.tools.adidas-group.com/#!result/14da02a4-0550-466c-826a-ae569e28bdc7/overview
![imagen](https://user-images.githubusercontent.com/38490820/94546062-a8a42880-024d-11eb-934c-63f554dfa46e.png)

I tested the same scenario again, same parameters, same everything, and the behaviour was the same.

Neoload test 2 link: http://neoloadweb.tools.adidas-group.com/#!result/a49c5674-30b8-4361-8706-10ca50df40d0/overview
![imagen](https://user-images.githubusercontent.com/38490820/94549484-98db1300-0252-11eb-9e81-7f3d507346f8.png)

Conclussions:

    - The AWS LoadBalancer ignores the MinReadySeconds Kubernetes configuration
    - The MinReadySeconds is useful to make the old pods live for a few minutes, to avoid them getting deleted as soon as the new pods get Ready
    - It seems that the AWS LoadBalancer takes maybe 2 minutes to find new pods, if the pod gets created in a new Kubernetes node, but it can route traffic instantly to new pods in old Kubernetes nodes (in Kubernetes nodes it already knew of)
    - As commented, we don't know for sure if the Github bug issue (https://github.com/Kong/kubernetes-ingress-controller/issues/581 ) would affect us or not. This bug was listed in the Kong IngressController milestone version 0.11.0 (it's only in the milestone, it doesn't mean it will be fixed in that version).

 

Fix suggestions:

    - In the short term, we could change the Rolling Update Max Surge to 20-50%, and have a MinReadySeconds of 150-180 seconds, This might be enough to have rolling updates without downtime. Not the best approach, it doesn't fix the problem, but might turn to be enough to avoid downtime.
    - In the mid-long term (or short term if possible), make the AWS Load Balancer find new Kong pods faster.

**Comment by ced0ps** [comment]
Current assumptions:
- When a new ingress controller comes up, it needs to sync configuration within the "mini cluster" of ingress controllers (due to db-less mode)
- Current readiness probe of ingress controller does not care about the sync status and announces readiness, as soon as the service is up
- This leads to traffic being sent to new pod, before it is aware of the endpoints it's expected to serve, which results in connection failures

Resolution:
- Either, pod does not state readiness until it's synced its configuration
- Or, proxy does not accept connections until config is synced

Next steps:
- Investigate if modification of readiness probe to check sync status is possible. If so, create PR upstream
- Temporarily, the pods readiness probe could probably be changed to use a command line call, to check sync status (this would have to be evaluated first)

**Comment by cadiegoc** [comment]
Hi team,

Since you haven't found a fix for this downtime issue yet, we wanted to make some deployments in Production trying to avoid downtime. Since we previously investigated the usage of the property **minReadySeconds** in the Kong Deployment.yaml (as it was reported in this ticket), we want to increase that value to 2-4 minutes.
But we don't know where can we add this value in our values.yaml file.

We checked your values.yaml (https://github.com/giantswarm/kong-app/blob/master/helm/kong-app/values.yaml ), and your Deployment.yaml template (https://github.com/giantswarm/kong-app/blob/master/helm/kong-app/templates/deployment.yaml), and we can't see that property:
![imagen](https://user-images.githubusercontent.com/38490820/96989035-6b1d7d00-1525-11eb-90d1-e5d64e7e72fe.png)

This property won't fix the problem with Kong, but we expect it will hide the downtime. And we might combine it with a maxSurge of 20-50%, so the old pods and new pods live at the same time while the new pods start accepting traffic.

Could you please add this property to your template, and let us know how to add it in our values.yaml?

We'll need this as soon as possible, since we're facing some issues at production, and to fix them, we need to redeploy Kong there, and we want to avoid downtime while doing it.

By the way, we're using the 0.9.1 version of the Kong chart, so we'd like this change to be availabie in both this version and in latest version, since we're going to face a "freeze period" in Adidas due to hype sales (singles day, Black Friday...), and we won't be able to deploy the latest version.

Please let us know as soon as you have included this parameter, since we want to test it as soon as possible (preferably today) so we can deploy it on Monday.

Thank you very much.

Best regards.

**Comment by Amzani** [comment]
@ced0ps  any updates on that ?

**Comment by ced0ps** [comment]
@Amzani Yes. The change was implemented and tested. I hit an issue creating the new release which I have not figured out yet. I'll take this on ASAP.

**Comment by ced0ps** [comment]
Release v0.9.2 is out. You can set the `minReadySeconds` as `deployment.kong.minReadySeconds` in the values.yaml

**Comment by cokiengchiara** [comment]
@ced0ps will update the issue and what needs to be done.

**Comment by cokiengchiara** [comment]
friendly reminder for @ced0ps

**Comment by cokiengchiara** [comment]
Fixed for customer. Upstream fix is not urgent. Will wait for @ced0ps to be back.

**Comment by othylmann** [comment]
all done some time already.

**Comment by cadiegoc** [comment]
Hi @othylmann ,
We did some some "hack" to try to avoid having downtime, but the issue "Kong readiness probe says it's ready when it's not" is not fixed.
